---
# Checks or performs Linux-Basics-1 lab tasks

- hosts: this_machine
  become: yes

  tasks:
    - debug:
        var: ansible_nodename
    - debug:
        var: ansible_user_dir 
    - import_role:
        name: file-system-basics
      tags:
        - file-system-basics
